# Generated by Django 5.0.3 on 2024-03-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='company_name',
        ),
        migrations.AddField(
            model_name='company',
            name='first_name',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='last_name',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
